import enum, uuid
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import String, DateTime, ForeignKey, Numeric, Integer, Boolean, JSON, UniqueConstraint, CheckConstraint
from sqlalchemy.orm import Mapped, mapped_column
from .db import Base

def uid(): return str(uuid.uuid4())
def now(): return datetime.now(timezone.utc)
class Tenant(Base):
    __tablename__="tenants"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(160)); status:Mapped[str]=mapped_column(String(20),default="pending"); plan_id:Mapped[str|None]=mapped_column(ForeignKey("pricing_plans.id")); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PricingPlan(Base):
    __tablename__="pricing_plans"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(80),unique=True); billing_type:Mapped[str]=mapped_column(String(20),default="prepaid"); markup_percent:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); http_tps:Mapped[int]=mapped_column(Integer,default=1); smpp_tps:Mapped[int]=mapped_column(Integer,default=1); monthly_quota:Mapped[int]=mapped_column(Integer,default=1000); max_api_keys:Mapped[int]=mapped_column(Integer,default=2); max_smpp_binds:Mapped[int]=mapped_column(Integer,default=1); config:Mapped[dict]=mapped_column(JSON,default=dict)
class BillingAccount(Base):
    __tablename__="billing_accounts"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),unique=True,index=True); currency:Mapped[str]=mapped_column(String(3),default="EUR"); billing_type:Mapped[str]=mapped_column(String(20),default="prepaid"); credit_limit:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); low_balance_threshold:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("10")); frozen:Mapped[bool]=mapped_column(Boolean,default=False); tax_metadata:Mapped[dict]=mapped_column(JSON,default=dict)
class Wallet(Base):
    __tablename__="wallets"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True); billing_account_id:Mapped[str]=mapped_column(ForeignKey("billing_accounts.id"),unique=True); currency:Mapped[str]=mapped_column(String(3)); available:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); reserved:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); pending:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); version:Mapped[int]=mapped_column(Integer,default=0)
class LedgerEntry(Base):
    __tablename__="ledger_entries"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key"),CheckConstraint("amount >= 0"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); billing_account_id:Mapped[str]=mapped_column(String(36)); currency:Mapped[str]=mapped_column(String(3)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); direction:Mapped[str]=mapped_column(String(6)); type:Mapped[str]=mapped_column(String(40)); reference_type:Mapped[str]=mapped_column(String(40)); reference_id:Mapped[str]=mapped_column(String(80)); idempotency_key:Mapped[str]=mapped_column(String(180)); actor:Mapped[str]=mapped_column(String(80)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class Reservation(Base):
    __tablename__="balance_reservations"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); billing_account_id:Mapped[str]=mapped_column(String(36)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); currency:Mapped[str]=mapped_column(String(3)); status:Mapped[str]=mapped_column(String(20),default="active"); idempotency_key:Mapped[str]=mapped_column(String(180)); message_id:Mapped[str]=mapped_column(String(36)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); finalized_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Rate(Base):
    __tablename__="rates"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); kind:Mapped[str]=mapped_column(String(20)); tenant_id:Mapped[str|None]=mapped_column(String(36),index=True); plan_id:Mapped[str|None]=mapped_column(String(36)); provider:Mapped[str|None]=mapped_column(String(80)); connector:Mapped[str|None]=mapped_column(String(80)); country:Mapped[str]=mapped_column(String(2)); network:Mapped[str|None]=mapped_column(String(20)); prefix:Mapped[str]=mapped_column(String(32)); currency:Mapped[str]=mapped_column(String(3)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); priority:Mapped[int]=mapped_column(Integer,default=0); effective_from:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); effective_to:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class Message(Base):
    __tablename__="messages"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); idempotency_key:Mapped[str]=mapped_column(String(180)); correlation_id:Mapped[str]=mapped_column(String(36)); destination:Mapped[str]=mapped_column(String(32)); sender:Mapped[str]=mapped_column(String(20)); content_hash:Mapped[str]=mapped_column(String(64)); encoding:Mapped[str]=mapped_column(String(10)); character_count:Mapped[int]=mapped_column(Integer); segments:Mapped[int]=mapped_column(Integer); provider:Mapped[str]=mapped_column(String(80)); provider_message_id:Mapped[str|None]=mapped_column(String(100)); status:Mapped[str]=mapped_column(String(30)); provider_rate_snapshot:Mapped[dict]=mapped_column(JSON); sell_rate_snapshot:Mapped[dict]=mapped_column(JSON); estimated_provider_cost:Mapped[Decimal]=mapped_column(Numeric(18,6)); estimated_sell_amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); actual_provider_cost:Mapped[Decimal|None]=mapped_column(Numeric(18,6)); actual_sell_amount:Mapped[Decimal|None]=mapped_column(Numeric(18,6)); reservation_id:Mapped[str|None]=mapped_column(String(36)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Usage(Base):
    __tablename__="usage_records"; __table_args__=(UniqueConstraint("tenant_id","message_id"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); message_id:Mapped[str]=mapped_column(String(36)); country:Mapped[str]=mapped_column(String(2)); provider:Mapped[str]=mapped_column(String(80)); sender:Mapped[str]=mapped_column(String(20)); segments:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(30)); revenue:Mapped[Decimal]=mapped_column(Numeric(18,6)); cost:Mapped[Decimal]=mapped_column(Numeric(18,6)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Invoice(Base):
    __tablename__="invoices"; __table_args__=(UniqueConstraint("tenant_id","number"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); number:Mapped[str]=mapped_column(String(40)); currency:Mapped[str]=mapped_column(String(3)); period_start:Mapped[datetime]=mapped_column(DateTime(timezone=True)); period_end:Mapped[datetime]=mapped_column(DateTime(timezone=True)); issue_date:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); due_date:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); subtotal:Mapped[Decimal]=mapped_column(Numeric(18,6)); tax:Mapped[Decimal]=mapped_column(Numeric(18,6),default=0); credits:Mapped[Decimal]=mapped_column(Numeric(18,6),default=0); total:Mapped[Decimal]=mapped_column(Numeric(18,6)); amount_paid:Mapped[Decimal]=mapped_column(Numeric(18,6),default=0); status:Mapped[str]=mapped_column(String(30),default="draft"); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class InvoiceLine(Base):
    __tablename__="invoice_lines"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); invoice_id:Mapped[str]=mapped_column(ForeignKey("invoices.id"),index=True); description:Mapped[str]=mapped_column(String(255)); quantity:Mapped[Decimal]=mapped_column(Numeric(18,6)); unit_price:Mapped[Decimal]=mapped_column(Numeric(18,6)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class Payment(Base):
    __tablename__="payments"; __table_args__=(UniqueConstraint("provider","provider_reference"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); provider:Mapped[str]=mapped_column(String(40)); provider_reference:Mapped[str]=mapped_column(String(120)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); currency:Mapped[str]=mapped_column(String(3)); status:Mapped[str]=mapped_column(String(30)); verified:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ApiKey(Base):
    __tablename__="api_keys"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); prefix:Mapped[str]=mapped_column(String(16),unique=True); secret_hash:Mapped[str]=mapped_column(String(255)); scopes:Mapped[str]=mapped_column(String(255),default="messages:write"); revoked:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); last_used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Audit(Base):
    __tablename__="audit_log"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str|None]=mapped_column(String(36),index=True); actor:Mapped[str]=mapped_column(String(100)); action:Mapped[str]=mapped_column(String(100)); target:Mapped[str]=mapped_column(String(120)); correlation_id:Mapped[str]=mapped_column(String(36)); before:Mapped[dict]=mapped_column(JSON,default=dict); after:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Outbox(Base):
    __tablename__="billing_outbox"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); event_type:Mapped[str]=mapped_column(String(80)); idempotency_key:Mapped[str]=mapped_column(String(180),unique=True); correlation_id:Mapped[str]=mapped_column(String(36)); envelope:Mapped[dict]=mapped_column(JSON); state:Mapped[str]=mapped_column(String(20),default="pending"); attempts:Mapped[int]=mapped_column(Integer,default=0); next_attempt_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); last_error:Mapped[str|None]=mapped_column(String(500)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
