import enum, uuid
from datetime import datetime, timezone
from decimal import Decimal
from sqlalchemy import String, DateTime, ForeignKey, Numeric, Integer, Boolean, JSON, UniqueConstraint, CheckConstraint
from sqlalchemy.orm import Mapped, mapped_column
from .db import Base

def uid(): return str(uuid.uuid4())
def now(): return datetime.now(timezone.utc)
class Tenant(Base):
    __tablename__="tenants"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(160)); status:Mapped[str]=mapped_column(String(20),default="pending"); plan_id:Mapped[str|None]=mapped_column(ForeignKey("pricing_plans.id")); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class PricingPlan(Base):
    __tablename__="pricing_plans"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(80),unique=True); billing_type:Mapped[str]=mapped_column(String(20),default="prepaid"); markup_percent:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); http_tps:Mapped[int]=mapped_column(Integer,default=1); smpp_tps:Mapped[int]=mapped_column(Integer,default=1); monthly_quota:Mapped[int]=mapped_column(Integer,default=1000); max_api_keys:Mapped[int]=mapped_column(Integer,default=2); max_smpp_binds:Mapped[int]=mapped_column(Integer,default=1); config:Mapped[dict]=mapped_column(JSON,default=dict)
class BillingAccount(Base):
    __tablename__="billing_accounts"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),unique=True,index=True); currency:Mapped[str]=mapped_column(String(3),default="EUR"); billing_type:Mapped[str]=mapped_column(String(20),default="prepaid"); credit_limit:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); low_balance_threshold:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("10")); frozen:Mapped[bool]=mapped_column(Boolean,default=False); tax_metadata:Mapped[dict]=mapped_column(JSON,default=dict)
class Wallet(Base):
    __tablename__="wallets"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(ForeignKey("tenants.id"),index=True); billing_account_id:Mapped[str]=mapped_column(ForeignKey("billing_accounts.id"),unique=True); currency:Mapped[str]=mapped_column(String(3)); available:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); reserved:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); pending:Mapped[Decimal]=mapped_column(Numeric(18,6),default=Decimal("0")); version:Mapped[int]=mapped_column(Integer,default=0)
class LedgerEntry(Base):
    __tablename__="ledger_entries"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key"),CheckConstraint("amount >= 0"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); billing_account_id:Mapped[str]=mapped_column(String(36)); currency:Mapped[str]=mapped_column(String(3)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); direction:Mapped[str]=mapped_column(String(6)); type:Mapped[str]=mapped_column(String(40)); reference_type:Mapped[str]=mapped_column(String(40)); reference_id:Mapped[str]=mapped_column(String(80)); idempotency_key:Mapped[str]=mapped_column(String(180)); actor:Mapped[str]=mapped_column(String(80)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class Reservation(Base):
    __tablename__="balance_reservations"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); billing_account_id:Mapped[str]=mapped_column(String(36)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); currency:Mapped[str]=mapped_column(String(3)); status:Mapped[str]=mapped_column(String(20),default="active"); idempotency_key:Mapped[str]=mapped_column(String(180)); message_id:Mapped[str]=mapped_column(String(36)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); finalized_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Rate(Base):
    __tablename__="rates"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); kind:Mapped[str]=mapped_column(String(20)); tenant_id:Mapped[str|None]=mapped_column(String(36),index=True); plan_id:Mapped[str|None]=mapped_column(String(36)); provider:Mapped[str|None]=mapped_column(String(80)); connector:Mapped[str|None]=mapped_column(String(80)); country:Mapped[str]=mapped_column(String(2)); network:Mapped[str|None]=mapped_column(String(20)); prefix:Mapped[str]=mapped_column(String(32)); currency:Mapped[str]=mapped_column(String(3)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); priority:Mapped[int]=mapped_column(Integer,default=0); effective_from:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); effective_to:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class Message(Base):
    __tablename__="messages"; __table_args__=(UniqueConstraint("tenant_id","idempotency_key"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); idempotency_key:Mapped[str]=mapped_column(String(180)); correlation_id:Mapped[str]=mapped_column(String(36)); destination:Mapped[str]=mapped_column(String(32)); sender:Mapped[str]=mapped_column(String(20)); content_hash:Mapped[str]=mapped_column(String(64)); encoding:Mapped[str]=mapped_column(String(10)); character_count:Mapped[int]=mapped_column(Integer); segments:Mapped[int]=mapped_column(Integer); provider:Mapped[str]=mapped_column(String(80)); provider_message_id:Mapped[str|None]=mapped_column(String(100)); status:Mapped[str]=mapped_column(String(30)); provider_rate_snapshot:Mapped[dict]=mapped_column(JSON); sell_rate_snapshot:Mapped[dict]=mapped_column(JSON); estimated_provider_cost:Mapped[Decimal]=mapped_column(Numeric(18,6)); estimated_sell_amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); actual_provider_cost:Mapped[Decimal|None]=mapped_column(Numeric(18,6)); actual_sell_amount:Mapped[Decimal|None]=mapped_column(Numeric(18,6)); reservation_id:Mapped[str|None]=mapped_column(String(36)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Usage(Base):
    __tablename__="usage_records"; __table_args__=(UniqueConstraint("tenant_id","message_id"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); message_id:Mapped[str]=mapped_column(String(36)); country:Mapped[str]=mapped_column(String(2)); provider:Mapped[str]=mapped_column(String(80)); sender:Mapped[str]=mapped_column(String(20)); segments:Mapped[int]=mapped_column(Integer); status:Mapped[str]=mapped_column(String(30)); revenue:Mapped[Decimal]=mapped_column(Numeric(18,6)); cost:Mapped[Decimal]=mapped_column(Numeric(18,6)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Invoice(Base):
    __tablename__="invoices"; __table_args__=(UniqueConstraint("tenant_id","number"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); number:Mapped[str]=mapped_column(String(40)); currency:Mapped[str]=mapped_column(String(3)); period_start:Mapped[datetime]=mapped_column(DateTime(timezone=True)); period_end:Mapped[datetime]=mapped_column(DateTime(timezone=True)); issue_date:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); due_date:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); subtotal:Mapped[Decimal]=mapped_column(Numeric(18,6)); tax:Mapped[Decimal]=mapped_column(Numeric(18,6),default=0); credits:Mapped[Decimal]=mapped_column(Numeric(18,6),default=0); total:Mapped[Decimal]=mapped_column(Numeric(18,6)); amount_paid:Mapped[Decimal]=mapped_column(Numeric(18,6),default=0); status:Mapped[str]=mapped_column(String(30),default="draft"); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class InvoiceLine(Base):
    __tablename__="invoice_lines"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); invoice_id:Mapped[str]=mapped_column(ForeignKey("invoices.id"),index=True); description:Mapped[str]=mapped_column(String(255)); quantity:Mapped[Decimal]=mapped_column(Numeric(18,6)); unit_price:Mapped[Decimal]=mapped_column(Numeric(18,6)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict)
class Payment(Base):
    __tablename__="payments"; __table_args__=(UniqueConstraint("provider","provider_reference"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); provider:Mapped[str]=mapped_column(String(40)); provider_reference:Mapped[str]=mapped_column(String(120)); amount:Mapped[Decimal]=mapped_column(Numeric(18,6)); currency:Mapped[str]=mapped_column(String(3)); status:Mapped[str]=mapped_column(String(30)); verified:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class ApiKey(Base):
    __tablename__="api_keys"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); prefix:Mapped[str]=mapped_column(String(16),unique=True); secret_hash:Mapped[str]=mapped_column(String(255)); scopes:Mapped[str]=mapped_column(String(255),default="messages:write"); revoked:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); last_used_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Audit(Base):
    __tablename__="audit_log"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str|None]=mapped_column(String(36),index=True); actor:Mapped[str]=mapped_column(String(100)); action:Mapped[str]=mapped_column(String(100)); target:Mapped[str]=mapped_column(String(120)); correlation_id:Mapped[str]=mapped_column(String(36)); before:Mapped[dict]=mapped_column(JSON,default=dict); after:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Outbox(Base):
    __tablename__="billing_outbox"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); event_type:Mapped[str]=mapped_column(String(80)); idempotency_key:Mapped[str]=mapped_column(String(180),unique=True); correlation_id:Mapped[str]=mapped_column(String(36)); envelope:Mapped[dict]=mapped_column(JSON); state:Mapped[str]=mapped_column(String(20),default="pending"); attempts:Mapped[int]=mapped_column(Integer,default=0); next_attempt_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); last_error:Mapped[str|None]=mapped_column(String(500)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)

# Product/control-plane records intentionally carry tenant_id directly.  API queries must
# always include it; the PostgreSQL migration additionally installs row-level security.
class TeamMember(Base):
    __tablename__="team_members"; __table_args__=(UniqueConstraint("tenant_id","email"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); email:Mapped[str]=mapped_column(String(255)); display_name:Mapped[str]=mapped_column(String(160)); role:Mapped[str]=mapped_column(String(40),default="tenant_user"); password_hash:Mapped[str]=mapped_column(String(255)); email_verified:Mapped[bool]=mapped_column(Boolean,default=False); mfa_secret_encrypted:Mapped[str|None]=mapped_column(String(512)); mfa_enabled:Mapped[bool]=mapped_column(Boolean,default=False); status:Mapped[str]=mapped_column(String(20),default="invited"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Sender(Base):
    __tablename__="senders"; __table_args__=(UniqueConstraint("tenant_id","sender"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); sender:Mapped[str]=mapped_column(String(20)); type:Mapped[str]=mapped_column(String(20),default="alphanumeric"); status:Mapped[str]=mapped_column(String(20),default="requested"); countries:Mapped[list]=mapped_column(JSON,default=list); rejection_reason:Mapped[str|None]=mapped_column(String(500)); metadata_json:Mapped[dict]=mapped_column("metadata",JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Contact(Base):
    __tablename__="contacts"; __table_args__=(UniqueConstraint("tenant_id","phone"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); phone:Mapped[str]=mapped_column(String(32)); name:Mapped[str|None]=mapped_column(String(160)); consent_status:Mapped[str]=mapped_column(String(24),default="unknown"); consent_source:Mapped[str|None]=mapped_column(String(120)); consent_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); consent_reference:Mapped[str|None]=mapped_column(String(255)); purpose:Mapped[str|None]=mapped_column(String(80)); opted_out_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); suppression_reason:Mapped[str|None]=mapped_column(String(255)); custom_fields:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Template(Base):
    __tablename__="templates"; __table_args__=(UniqueConstraint("tenant_id","name"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); name:Mapped[str]=mapped_column(String(120)); content:Mapped[str]=mapped_column(String(5000)); category:Mapped[str]=mapped_column(String(30),default="transactional"); status:Mapped[str]=mapped_column(String(20),default="draft"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Campaign(Base):
    __tablename__="campaigns"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); name:Mapped[str]=mapped_column(String(160)); template_id:Mapped[str|None]=mapped_column(String(36)); sender_id:Mapped[str|None]=mapped_column(String(36)); category:Mapped[str]=mapped_column(String(30),default="marketing"); status:Mapped[str]=mapped_column(String(24),default="draft"); scheduled_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); timezone:Mapped[str]=mapped_column(String(80),default="UTC"); recipient_count:Mapped[int]=mapped_column(Integer,default=0); estimated_segments:Mapped[int]=mapped_column(Integer,default=0); estimated_cost:Mapped[Decimal]=mapped_column(Numeric(18,6),default=0); approval_required:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Webhook(Base):
    __tablename__="webhooks"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); url:Mapped[str]=mapped_column(String(500)); events:Mapped[list]=mapped_column(JSON,default=list); secret_hash:Mapped[str]=mapped_column(String(255)); secret_ciphertext:Mapped[str]=mapped_column(String(1000)); enabled:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class WebhookDelivery(Base):
    __tablename__="webhook_deliveries"; __table_args__=(UniqueConstraint("webhook_id","event_id"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); webhook_id:Mapped[str]=mapped_column(String(36),index=True); event_id:Mapped[str]=mapped_column(String(36)); status:Mapped[str]=mapped_column(String(20),default="pending"); attempts:Mapped[int]=mapped_column(Integer,default=0); response_code:Mapped[int|None]=mapped_column(Integer); next_attempt_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Provider(Base):
    __tablename__="providers"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); name:Mapped[str]=mapped_column(String(120),unique=True); connector:Mapped[str]=mapped_column(String(80),unique=True); state:Mapped[str]=mapped_column(String(20),default="disabled"); health_score:Mapped[int]=mapped_column(Integer,default=100); circuit_state:Mapped[str]=mapped_column(String(20),default="closed"); tps:Mapped[int]=mapped_column(Integer,default=1); latency_ms:Mapped[int]=mapped_column(Integer,default=0); capabilities:Mapped[dict]=mapped_column(JSON,default=dict); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Route(Base):
    __tablename__="routes"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str|None]=mapped_column(String(36),index=True); country:Mapped[str]=mapped_column(String(2)); prefix:Mapped[str]=mapped_column(String(32)); sender_type:Mapped[str|None]=mapped_column(String(20)); provider_id:Mapped[str]=mapped_column(String(36)); priority:Mapped[int]=mapped_column(Integer,default=0); enabled:Mapped[bool]=mapped_column(Boolean,default=False); version:Mapped[int]=mapped_column(Integer,default=1); config:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class MessageEvent(Base):
    __tablename__="message_events"; __table_args__=(UniqueConstraint("tenant_id","external_event_id"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); message_id:Mapped[str]=mapped_column(String(36),index=True); external_event_id:Mapped[str]=mapped_column(String(120)); type:Mapped[str]=mapped_column(String(40)); status:Mapped[str]=mapped_column(String(30)); provider_response:Mapped[dict]=mapped_column(JSON,default=dict); occurred_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class InboundMessage(Base):
    __tablename__="inbound_messages"; __table_args__=(UniqueConstraint("provider","provider_message_id"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); provider:Mapped[str]=mapped_column(String(80)); provider_message_id:Mapped[str]=mapped_column(String(120)); sender:Mapped[str]=mapped_column(String(32)); destination:Mapped[str]=mapped_column(String(32)); content:Mapped[str]=mapped_column(String(5000)); contact_id:Mapped[str|None]=mapped_column(String(36)); conversation_key:Mapped[str]=mapped_column(String(100),index=True); unread:Mapped[bool]=mapped_column(Boolean,default=True); assigned_to:Mapped[str|None]=mapped_column(String(36)); tags:Mapped[list]=mapped_column(JSON,default=list); received_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class SmppCredential(Base):
    __tablename__="smpp_credentials"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); system_id:Mapped[str]=mapped_column(String(32),unique=True); password_hash:Mapped[str]=mapped_column(String(255)); bind_mode:Mapped[str]=mapped_column(String(16),default="transceiver"); max_binds:Mapped[int]=mapped_column(Integer,default=1); tps:Mapped[int]=mapped_column(Integer,default=1); ip_allowlist:Mapped[list]=mapped_column(JSON,default=list); enabled:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class CountryPolicy(Base):
    __tablename__="country_policies"; __table_args__=(UniqueConstraint("country","category"),); id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); country:Mapped[str]=mapped_column(String(2)); category:Mapped[str]=mapped_column(String(30)); stop_keywords:Mapped[list]=mapped_column(JSON,default=lambda:["STOP"]); help_keywords:Mapped[list]=mapped_column(JSON,default=lambda:["HELP"]); quiet_hours:Mapped[dict]=mapped_column(JSON,default=dict); config:Mapped[dict]=mapped_column(JSON,default=dict); enabled:Mapped[bool]=mapped_column(Boolean,default=False)
class AuthToken(Base):
    __tablename__="auth_tokens"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); tenant_id:Mapped[str]=mapped_column(String(36),index=True); member_id:Mapped[str]=mapped_column(String(36),index=True); kind:Mapped[str]=mapped_column(String(20)); token_hash:Mapped[str]=mapped_column(String(64),unique=True); csrf_hash:Mapped[str|None]=mapped_column(String(64)); user_agent_hash:Mapped[str|None]=mapped_column(String(64)); ip_hash:Mapped[str|None]=mapped_column(String(64)); expires_at:Mapped[datetime]=mapped_column(DateTime(timezone=True)); revoked_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class LoginAttempt(Base):
    __tablename__="login_attempts"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); identity_hash:Mapped[str]=mapped_column(String(64),index=True); ip_hash:Mapped[str]=mapped_column(String(64),index=True); succeeded:Mapped[bool]=mapped_column(Boolean,default=False); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True)
